### ISSUE TITLE
user part contains a comma

### ISSUE THREAD

**Issue by prognostikos** [substancelab/activemodel-email_address_validator#27]
Looks like `foo,bar@gmail.com` is considered valid and I guess it could be technically. We want to disallow it, however. Would you accept a PR for this or should we just handle it in our app?

**Comment by koppen** [comment]
This is exactly the kind of restrictions we want in this validator. Sure, it might technically be possible to have a comma in your email address, but...

1. I have never seen an email address with a comma
2. Most (all?) email clients I have ever used use comma as a separator, I don't even know how I'd type a comma in a recipient address
3. Accidentally fatfingering a `,` instead of a `.` when entering your email address is an easy mistake to make, let's help people avoid that.

👍

**Comment by prognostikos** [comment]
@koppen it could make sense to switch to whitelisting characters allowed in the user portion, e.g. I think `_ - + .` might be good enough for 99% of email addresses.

**Comment by prognostikos** [comment]
Looking at one app with 460k emails `/[^[:word:]\d\.\+\_\-]/i` seems to do the right thing.
